export const CONTENT_PLAN = [
  {
    id: 1,
    batch: 1,
    type: 'tutorials',
    slug: 'getting-started/installation',
    titleEn: 'How to Install Hermes Agent on Any Platform',
    titleZh: '全平台安装 Hermes Agent：5 分钟搞定',
  },
  {
    id: 2,
    batch: 1,
    type: 'tutorials',
    slug: 'getting-started/first-conversation',
    titleEn: 'Your First Conversation: What to Say and How',
    titleZh: '第一次对话：怎么和 AI Agent 聊出效率',
  },
  {
    id: 3,
    batch: 1,
    type: 'tutorials',
    slug: 'getting-started/choosing-a-model',
    titleEn: 'How to Choose the Right AI Model for Your Workflow',
    titleZh: '模型选择指南：省钱、快速、聪明，选哪个？',
  },
  {
    id: 4,
    batch: 2,
    type: 'tutorials',
    slug: 'getting-started/cli-essentials',
    titleEn: "15 CLI Commands You'll Use Every Day",
    titleZh: '每天都在用的 15 个 CLI 命令（含速查表）',
  },
  {
    id: 5,
    batch: 2,
    type: 'tutorials',
    slug: 'getting-started/configuration-guide',
    titleEn: 'The Complete Configuration Guide: config.yaml Explained',
    titleZh: '配置文件完全指南：每个参数都讲清楚',
  },
  {
    id: 6,
    batch: 2,
    type: 'tutorials',
    slug: 'getting-started/openclaw-migration',
    titleEn: 'Migrating from OpenClaw Without Losing Anything',
    titleZh: '从 OpenClaw 迁移：数据、技能、记忆一个不丢',
  },
  {
    id: 7,
    batch: 3,
    type: 'tutorials',
    slug: 'messaging/telegram-bot-setup',
    titleEn: 'Set Up Hermes on Telegram in 10 Minutes',
    titleZh: '10 分钟搞定 Telegram 上的 AI 管家',
  },
  {
    id: 8,
    batch: 3,
    type: 'tutorials',
    slug: 'messaging/discord-integration',
    titleEn: 'Build an AI Bot for Your Discord Community',
    titleZh: '给 Discord 社区加一个 AI 助手',
  },
  {
    id: 9,
    batch: 3,
    type: 'tutorials',
    slug: 'messaging/multi-platform-connect',
    titleEn: 'Connect Hermes to Slack, WhatsApp & Signal',
    titleZh: '一个 Agent 连全部：Slack/WhatsApp/Signal',
  },
  {
    id: 10,
    batch: 3,
    type: 'tutorials',
    slug: 'messaging/multi-platform-gateway',
    titleEn: 'Multi-Platform Gateway: Architecture Deep Dive',
    titleZh: '多平台网关架构：一张图讲清楚',
  },
  {
    id: 11,
    batch: 4,
    type: 'tutorials',
    slug: 'skills/install-community-skills',
    titleEn: 'Browse & Install Skills: Give Hermes Superpowers',
    titleZh: '给 Hermes 装技能：3 分钟扩展 AI 能力',
  },
  {
    id: 12,
    batch: 4,
    type: 'tutorials',
    slug: 'skills/create-custom-skills',
    titleEn: 'Create Your First Skill from Scratch',
    titleZh: '手搓一个自定义技能（含完整代码）',
  },
  {
    id: 13,
    batch: 4,
    type: 'tutorials',
    slug: 'skills/skill-development-best-practices',
    titleEn: 'Skill Development: Patterns, Tests, and Best Practices',
    titleZh: '技能开发最佳实践：代码模式 + 测试',
  },
  {
    id: 14,
    batch: 4,
    type: 'tutorials',
    slug: 'skills/self-learning-loop',
    titleEn: 'How the Self-Learning Loop Actually Works',
    titleZh: 'AI 怎么自己学会新技能？闭环机制详解',
  },
  {
    id: 15,
    batch: 5,
    type: 'tutorials',
    slug: 'automation/cron-scheduling',
    titleEn: 'Automate Anything with Cron: A Practical Guide',
    titleZh: '定时任务终极指南：让 AI 自动帮你干活',
  },
  {
    id: 16,
    batch: 5,
    type: 'tutorials',
    slug: 'automation/daily-report-system',
    titleEn: 'Build an Automated Daily Report System',
    titleZh: '每天早上自动发日报，老板都惊了',
  },
  {
    id: 17,
    batch: 5,
    type: 'tutorials',
    slug: 'automation/server-monitoring-alerts',
    titleEn: 'Server Monitoring & Smart Alerts with Hermes',
    titleZh: '服务器异常？AI 比你先知道还帮你修',
  },
  {
    id: 18,
    batch: 5,
    type: 'tutorials',
    slug: 'automation/automation-recipes',
    titleEn: '10 Real-World Automation Recipes You Can Copy',
    titleZh: '10 个拿来就用的自动化方案（附代码）',
  },
  {
    id: 19,
    batch: 6,
    type: 'tutorials',
    slug: 'advanced/multi-agent-orchestration',
    titleEn: 'Multi-Agent Orchestration: Patterns That Work',
    titleZh: '多 Agent 编排：3 种实战模式',
  },
  {
    id: 20,
    batch: 6,
    type: 'tutorials',
    slug: 'advanced/mcp-integration',
    titleEn: 'MCP Integration: Connect GitHub, Notion & More',
    titleZh: 'MCP 实战：接 GitHub / Notion / 数据库',
  },
  {
    id: 21,
    batch: 6,
    type: 'tutorials',
    slug: 'advanced/memory-system-deep-dive',
    titleEn: 'Memory System Deep Dive: How Hermes Remembers',
    titleZh: '记忆系统拆解：AI 为什么会忘事？怎么治',
  },
  {
    id: 22,
    batch: 6,
    type: 'tutorials',
    slug: 'advanced/parallel-sub-agents',
    titleEn: 'Parallel Sub-Agents: Run 5 Tasks at Once',
    titleZh: '并行子 Agent：5 个任务同时跑',
  },
  {
    id: 23,
    batch: 6,
    type: 'tutorials',
    slug: 'advanced/architecture-walkthrough',
    titleEn: 'Architecture Walkthrough: Hermes Source Code',
    titleZh: '源码解读：Hermes Agent 架构拆解',
  },
  {
    id: 24,
    batch: 7,
    type: 'guides',
    slug: 'deployment/vps-setup',
    titleEn: 'Deploy Hermes 24/7 on a $5 VPS',
    titleZh: '$5/月：7×24 小时运行你的 AI Agent',
  },
  {
    id: 25,
    batch: 7,
    type: 'guides',
    slug: 'deployment/docker-production',
    titleEn: 'Production Docker Deployment with Monitoring',
    titleZh: 'Docker 生产部署 + Prometheus 监控',
  },
  {
    id: 26,
    batch: 7,
    type: 'guides',
    slug: 'deployment/modal-serverless',
    titleEn: 'Run Hermes Serverless with Modal',
    titleZh: '无服务器部署：按用量付费不浪费',
  },
  {
    id: 27,
    batch: 7,
    type: 'guides',
    slug: 'security/hardening-checklist',
    titleEn: 'Security Hardening Checklist (32 Items)',
    titleZh: '安全加固清单：32 项逐个检查',
  },
  {
    id: 28,
    batch: 7,
    type: 'guides',
    slug: 'comparisons/hermes-vs-autogpt',
    titleEn: 'Hermes vs AutoGPT: Honest Comparison',
    titleZh: 'Hermes vs AutoGPT：到底选哪个？',
  },
  {
    id: 29,
    batch: 7,
    type: 'guides',
    slug: 'comparisons/hermes-vs-open-interpreter',
    titleEn: 'Hermes vs Open Interpreter: Use Cases Compared',
    titleZh: 'Hermes vs Open Interpreter：场景化对比',
  },
  {
    id: 30,
    batch: 7,
    type: 'blog',
    slug: '2026/hermes-v08-changelog',
    titleEn: "What's New in v0.8: Complete Changelog Analysis",
    titleZh: 'v0.8 更新了什么？完整变更解读',
  },
];

export const PLAN_LOCALES = ['en', 'zh'];
